import { marked } from 'marked';
import { NodeHtmlMarkdown } from 'node-html-markdown';

const nhm = new NodeHtmlMarkdown(
    {},
    undefined,
    undefined
);

class MarkdownConverterService {
    /**
     * Converts raw Markdown to HTML to be displayed inside the Rich Text Editor.
     * @param markdown The raw markdown content.
     * @returns HTML string.
     */
    static markdownToHtml(markdown: string): string {
        if (!markdown) return '';
        try {
            // Marked parse returns a string or Promise depending on config.
            // By default with no async plugins, it returns string.
            // We use gfm: true by default.
            let html = marked.parse(markdown, { gfm: true, breaks: true }) as string;

            // Convert marked's disabled checkboxes to pell's active x-todo structure
            // Marked formats checklists as: <input checked="" disabled="" type="checkbox">
            html = html.replace(/<input\s+(checked="")?\s*disabled=""\s*type="checkbox">/gi, (match, checked) => {
                const isChecked = !!checked;
                return `<span contenteditable="false" class="x-todo-box"><input type="checkbox"${isChecked ? ' checked="true"' : ''}></span>`;
            });

            // Marked sometimes wraps list items in <p>. Unwrap them for Pell checkboxes
            html = html.replace(/<li>\s*<p>(<span[^>]+x-todo-box[^>]+>.*?<\/span>)(.*?)<\/p>\s*<\/li>/gi, '<li>$1$2</li>');
            
            // Pell's checkbox list is implemented as <ol class="x-todo">, not <ul>.
            // The Enter key handler in pell editor.js checks queryCommandState('insertOrderedList'),
            // which only returns true for <ol> elements. Using <ul> breaks Enter continuation —
            // new <li> items are created without a checkbox span.
            // Solution: convert the <ul> wrapping x-todo-box items to <ol class="x-todo">,
            // and close it with </ol> instead of </ul>.
            html = html.replace(/<ul>((?:(?!<\/ul>)[\s\S])*?x-todo-box(?:(?!<\/ul>)[\s\S])*?)<\/ul>/gi,
                '<ol class="x-todo">$1</ol>');

            return html;
        } catch (error) {
            console.error('Error converting Markdown to HTML:', error);
            return '<p>Error loading content.</p>';
        }
    }

    /**
     * Converts HTML from the Rich Text Editor back into raw Markdown for storage.
     * @param html The HTML content generated by the Rich Text Editor.
     * @returns Raw markdown string.
     */
    static htmlToMarkdown(html: string): string {
        if (!html) return '';
        try {
            // 1. Pre-process HTML: Convert Pell's checkbox spans into raw text "[ ] " or "[x] "
            // We check for the presence of 'checked' anywhere in the span instead of trying to
            // capture it with a regex group — [^>]* would greedily consume the 'checked' attribute
            // before the capture group could see it.
            let preProcessedHtml = html.replace(/<span[^>]*class="x-todo-box"[^>]*>.*?<\/span>/gi, (match) => {
                return /checked/.test(match) ? '[x] ' : '[ ] ';
            });

            // Remove the x-todo class so NHM doesn't do anything weird
            preProcessedHtml = preProcessedHtml.replace(/ class="x-todo"/gi, '');

            let md = nhm.translate(preProcessedHtml);

            // 2. Post-process MD: NHM escapes the brackets as \[ \] and \[x\]. Revert them back.
            // Also, it might prefix them with "* \[ \]". We want standard "- [ ]".
            md = md.replace(/\* \\\[ \\\] /g, '- [ ] ');
            md = md.replace(/\* \\\[x\\\] /gi, '- [x] ');
            
            // Handle Pell's <ol> checklists which might render as "1. \[ \]"
            md = md.replace(/\d+\. \\\[ \\\] /g, '- [ ] ');
            md = md.replace(/\d+\. \\\[x\\\] /gi, '- [x] ');

            return md;
        } catch (error) {
            console.error('Error converting HTML to Markdown:', error);
            // Fallback: strip script/style blocks first, then all remaining tags
            return html
                .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
                .replace(/<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>/gi, '')
                .replace(/<[^>]+>/g, '');
        }
    }
}

export default MarkdownConverterService;
